version: "3.8"

services:
  fooocus-api:
    image: konieshadow/fooocus-api:latest
    container_name: fooocus-api
    restart: unless-stopped
    command: python3 main.py --host 0.0.0.0 --port 8888 --baseurl ${BASE_URL}
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - fooocus-api-repo:/app/repositories
      - fooocus-api-cache:/root/.cache/pip
    ports:
      - "8888:8888/tcp"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  fooocus-api-cache:
  fooocus-api-repo:
